name: build

on:
    push:
        branches: [CI-CD]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Setup .NET
          uses: actions/setup-dotnet@v2
          with:
              dotnet-version: 6.0.x
        - name: Install dependencies
          run: dotnet restore
          working-directory: phase5
        - name: Build
          run: dotnet build --configuration Release --no-restore
          working-directory: phase5
        - name: Test
          run: dotnet test --no-restore --verbosity normal --collect:"XPlat Code Coverage"
          working-directory: phase5
        - name: Publish code coverage reports to codecove.io
          uses: codecov/codecov-action@v1
          with:
              token: 556f3ce3-dd2c-47e8-b1a5-64abff143b7b
              files: ./**/coverage.cobertura.xml
              fail_ci_if_error: true